CREATE TABLE indragt3.locations (
  LOCATION_ID INT NOT NULL,
  STREET_ADDRESS VARCHAR(45) NULL,
  POSTAL_CODE VARCHAR(45) NULL,
  CITY VARCHAR(45) NOT NULL,
  STATE_PROVINCE VARCHAR(45) NULL,
  COUNTRY_ID CHAR(2) NULL,
  PRIMARY KEY (LOCATION_ID));
